////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was not generated by a tool. but for stylecop suppression.
//// </auto-generated>
////------------------------------------------------------------------------------
namespace StrixIT.Platform.Modules.Logging.Migrations
{
    using System.Data.Entity.Migrations;

    internal sealed class Configuration : DbMigrationsConfiguration<StrixIT.Platform.Modules.Logging.LoggingDataSource>
    {
        #region Public Constructors

        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        #endregion Public Constructors

        #region Protected Methods

        protected override void Seed(StrixIT.Platform.Modules.Logging.LoggingDataSource context)
        {
        }

        #endregion Protected Methods
    }
}