//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Entity;

namespace StrixIT.Platform.Modules.Logging.Tests
{
    public class TestLoggingSourceInitializer : DropCreateDatabaseAlways<TestLoggingSource>
    {
    }
}
