//------------------------------------------------------------------------------
// <auto-generated>
//     This code was not generated by a tool. but for stylecop suppression.
// </auto-generated>
//------------------------------------------------------------------------------
using StrixIT.Platform.Core;
using System.Data.Entity;

namespace StrixIT.Platform.Modules.Logging.Tests
{
    public class TestLoggingSource : LoggingDataSource
    {
        #region Public Constructors

        public TestLoggingSource(IConfiguration config) : base(config)
        {
            Database.SetInitializer<TestLoggingSource>(new TestLoggingSourceInitializer());
        }

        #endregion Public Constructors
    }
}